#!/bin/bash
custom_readlink() { [ ! -h "$1" ] && echo "$1" || (local link="$(expr "$(command ls -ld -- "$1")" : '.*-> \(.*\)$')"; cd $(dirname $1); custom_readlink "$link" | sed "s|^\([^/].*\)\$|$(dirname $1)/\1|"); }
npm_path=`dirname "$(custom_readlink ${BASH_SOURCE[0]})"`

user=$(who am i)
if [ -z "$user" ]; then
	user=$(whoami)
fi

user=$( echo "$user" | awk '{print $1}')
if [ -e /home/$user/.bashrc ]; then
	source_file="/home/$user/.bashrc"
elif [ -e /Users/$user/.bash_profile ]; then
	source_file="/Users/$user/.bash_profile"
else
	user2=$(echo $user | sed 's/.*[\/\\]//')
	if [ -e /c/Users/$user/.bashrc ]; then
		source_file="/c/Users/$user/.bashrc"
	elif [ -e /c/Users/$user2/.bashrc ]; then
		user=$user2
		source_file="/c/Users/$user/.bashrc"
	fi
fi

if [ ! -z $source_file ]; then
	bash_comment="# added for npm-completion https://github.com/Jephuff/npm-bash-completion"
	bash_variable="PATH_TO_NPM_COMPLETION=\"$npm_path\""
	npm_source="source \$PATH_TO_NPM_COMPLETION/npm-completion.sh"

	grep -F "$bash_comment" $source_file > /dev/null
	if [ $? != 0 ]; then
		printf "\n$bash_comment" >> $source_file
	fi

	grep -F "$bash_variable" $source_file > /dev/null
	if [ $? != 0 ]; then
		printf "\n$bash_variable" >> $source_file
	fi

	grep -F "$npm_source" $source_file > /dev/null
	if [ $? != 0 ]; then
		printf "\n$npm_source" >> $source_file
	fi

	echo -e "\nadd this line to a cron job or startup script"
	echo "    PATH=\$PATH:$(dirname $(which node)):$(dirname $(which npm)) && cd $npm_path && ./update"
	echo -e "\nrestart terminal to start using\n"
else
	echo -e "\ncouldn't find ~/.bashrc or ~/.bash_profile. Please create one of these file and run\n    npm-completion-setup\n"
fi
