#!/bin/bash
TARGET_FILE=${BASH_SOURCE[0]}
cd "dirname $TARGET_FILE"
TARGET_FILE=`basename $TARGET_FILE`
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done
PHYS_DIR=`pwd -P`
npm_path=`dirname $PHYS_DIR/$TARGET_FILE`

user=$(who am i | awk '{print $1}')
if [ -e /home/$user/.bashrc ]; then
	source_file="/home/$user/.bashrc"
elif [ -e /Users/$user/.bash_profile ]; then
	source_file="/Users/$user/.bash_profile"
fi

if [ ! -z $source_file ]; then
	bash_comment="# added for npm-completion"
	bash_variable="PATH_TO_NPM_COMPLETION"
	npm_source=". \$PATH_TO_NPM_COMPLETION\/npm-completion.sh"

	sed -i "/$bash_comment/d" $source_file
	sed -i "/$bash_variable/d" $source_file
	sed -i "/$npm_source/d" $source_file
fi

echo "remove this line to a cron job or startup script if added"
echo "    cd $npm_path && ./update.sh"
