#!/bin/bash
TARGET_FILE=${BASH_SOURCE[0]}
cd "dirname $TARGET_FILE"
TARGET_FILE=`basename $TARGET_FILE`
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done
PHYS_DIR=`pwd -P`
npm_path=`dirname $PHYS_DIR/$TARGET_FILE`

cd $npm_path
if [ -d .git ]; then
	git pull
else
	npm update -g npm-completion
fi
