#!/bin/sh
custom_readlink() { [ ! -h "$1" ] && echo "$1" || (local link="$(expr "$(command ls -ld -- "$1")" : '.*-> \(.*\)$')"; cd $(dirname $1); custom_readlink "$link" | sed "s|^\([^/].*\)\$|$(dirname $1)/\1|"); }
if [ -d .git ]; then
  cd $( dirname $(custom_readlink $0) )
  git pull
else
  npm i -g npm-completion
fi
